### ISSUE TITLE
Port to macOS application?

### ISSUE THREAD

**Issue by carmenchui** [mmaroti/prover9-mace4#1]
Hi @mmaroti,

I was wondering if it is possible to port your modernization of the Prover9 source code into a macOS application (as a *.app file).

With the latest macOS operating system (OS X 10.15.6 "Catalina"), all support for 32-bit applications has been dropped, so the original Prover9-Mace4 macOS binary from William McCune's website (https://www.cs.unm.edu/~mccune/prover9/gui/v05.html) can no longer be used on newer versions of macOS.

Do you know if it is possible to use py2app (http://undefined.org/python/py2app.html) with your modernized code to generate the .app file?

Thanks,
Carmen

**Comment by mmaroti** [comment]
Hmm, I am not sure. I do not have access to macOS, so it will be very hard for me to test or do anything about it. One question: if you just clone this application and run it then what happens? Does the prover9 and mace4 binaries (not the GUI) work for you? I guess that is also a 32-bit application, so the problem starts there, no?

**Comment by carmenchui** [comment]
Hi @mmaroti, 

The prover9 and mace4 binaries work without issues in command-line on my Mac.  I cannot seem to get your GUI code to work on my MacBook since I had some issues installing python-wxgtk3.0, but I'll try to investigate that later.

I have tried installing your code on an Ubuntu virtual machine, but came across some issues with the GUI:
- buttons do not work and errors show up in Terminal when I press them; this error occurs:
`(prover9-mace4.py:29240): Gtk-CRITICAL **: 14:52:57.604: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Traceback (most recent call last):
  File "/home/carmen/prover9-mace4/my_setup.py", line 148, in well_formed_check
    (exit, message, error) = syntax_check(input)
  File "/home/carmen/prover9-mace4/control.py", line 1109, in syntax_check
    (exit_code,output,err) = run_and_wait(prover9_command, input=input2)
  File "/home/carmen/prover9-mace4/control.py", line 49, in run_and_wait
    process = subprocess.Popen(command,stdin=fin,stdout=fout,stderr=ferr)
  File "/usr/lib/python2.7/subprocess.py", line 394, in init
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`
- Prover9 and Mace4 do not actually start (screenshot below; the sample file is Kaeur.in)
![2020-09-16_14-59-44](https://user-images.githubusercontent.com/4117565/93380595-6b8f6d80-f82d-11ea-8263-9db4a1ce290b.jpg)


I am using the following on my VM:
```
carmen@carmen-VirtualBox:~/prover9-mace4$ apt list python-wxgtk3.0
Listing... Done
python-wxgtk3.0/focal,now 3.0.2.0+dfsg-8build1 amd64 [installed]
carmen@carmen-VirtualBox:~/prover9-mace4$ python2 --version
Python 2.7.18rc1
carmen@carmen-VirtualBox:~/prover9-mace4$ python3 --version
Python 3.8.2
carmen@carmen-VirtualBox:~/prover9-mace4$ hostnamectl
   Static hostname: carmen-VirtualBox
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 596d2fd180294bb683a7b211189825ed
           Boot ID: 78a9299bf2174c22aebb18bcb3ed59ad
    Virtualization: oracle
  Operating System: Ubuntu 20.04.1 LTS
            Kernel: Linux 5.4.0-47-generic
      Architecture: x86-64
```

Can you let me know which version of Ubuntu you used to compile your Prover9-Mace4 modernization?

Thank you.
